//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coditech.DataAccessLayer.DataEntity
{
    using System;

    public partial class UserType: CoditechEntityBaseModel
    {
        public short UserTypeId { get; set; }
        public string UserTypeCode { get; set; }
        public string UserDescription { get; set; }
        public string RelatedWith { get; set; }
        public bool IsCommon { get; set; }
        public bool IsLoginRequired { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
